name: dms-laptop-os
description: Official DMS Experience on uBlue F43
base-image: ghcr.io/ublue-os/base-main
image-version: 43

modules:
  - type: files
    files:
      - source: /usr
        destination: /usr
 
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/avengemedia/danklinux/repo/fedora-43/avengemedia-danklinux-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/avengemedia/dms/repo/fedora-43/avengemedia-dms-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/ashbuk/Hyprland-Fedora/repo/fedora-43/ashbuk-Hyprland-Fedora-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/agonie/swww/repo/fedora-43/agonie-swww-fedora-43.repo

    install:
      - dms
      - dgop
      - hyprland
      - hyprland-guiutils
      - greetd
      - dms-greeter
      - quickshell 
      - xorg-x11-server-Xwayland
      - adw-gtk3-theme
      - matugen
      - cava
      - qt6-qtwayland
      - qt6-qtdeclarative
      - qt6ct
      - qt6-qtmultimedia
      - qt6-qtshadertools
      - qt6-qtimageformats
      - kf6-kimageformats
      - jemalloc 
      - nemo
      - nemo-fileroller
      - kitty
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - xdg-desktop-portal-hyprland 
      - xdg-desktop-portal-gtk      
      - gnome-keyring               
      - power-profiles-daemon
      - cups
      - accountsservice
      - grim
      - slurp
      - playerctl
      - swww
      - rsms-inter-fonts
      - khal
      - cups-pk-helper
      - fprintd 
      - fprintd-pam
      - jq
      - tailscale
      - polkit-gnome

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - io.github.kolunmi.Bazaar    
          - dev.zed.Zed                 
          - app.zen_browser.zen   

  - type: script
    scripts:
      - permissions.sh

  - type: systemd
    system:
      enabled:
        - greetd.service
        - tailscaled.service
