name: dms-laptop-os
description: Official DMS Experience on uBlue F43
base-image: ghcr.io/ublue-os/base-main
image-version: 43

modules:
  - type: files
    files:
      - source: /usr
        destination: /usr

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/avengemedia/danklinux/repo/fedora-43/avengemedia-danklinux-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/avengemedia/dms/repo/fedora-43/avengemedia-dms-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/ferdiu/libfprint-tod/repo/fedora-43/ferdiu-libfprint-tod-fedora-43.repo
      - https://copr.fedorainfracloud.org/coprs/nett00n/hyprland/repo/fedora-43/nett00n-hyprland-fedora-43.repo
    install:
      - dms
      - dgop
      - hyprland
      - hyprland-guiutils
      - greetd
      - dms-greeter
      - quickshell 
      - xorg-x11-server-Xwayland
      - adw-gtk3-theme
      - matugen
      - cava
      - qt6-qtwayland
      - qt6-qtdeclarative
      - qt6ct
      - qt6-qtmultimedia
      - qt6-qtshadertools
      - qt6-qtimageformats
      - kf6-kimageformats
      - jemalloc 
      - nemo
      - nemo-fileroller
      - nemo-terminal
      - nemo-preview
      - kitty
      - zsh
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - xdg-desktop-portal-hyprland 
      - xdg-desktop-portal-gtk      
      - gnome-keyring       
      - gnome-keyring-pam
      - power-profiles-daemon
      - cups
      - accountsservice
      - grim
      - slurp
      - playerctl
      - rsms-inter-fonts
      - khal
      - cups-pk-helper
      - fprintd 
      - fprintd-pam
      - jq
      - tailscale
      - lxqt-policykit
      - imv
      - xdg-user-dirs
      - steam-devices
      - swappy
      - libfprint-tod
      - gamescope 

  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - io.github.kolunmi.Bazaar    
          - dev.zed.Zed                 
          - app.zen_browser.zen 
          - com.valvesoftware.Steam
          - com.moonlight_stream.Moonlight
          - com.github.tchx84.Flatseal  
          - io.github.celluloid_player.Celluloid
          - org.videolan.VLC
          - org.onlyoffice.desktopeditors
          - me.proton.Mail
          - io.missioncenter.MissionCenter
          - org.localsend.localsend_app

  - type: script
    scripts:
      - permissions.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: systemd
    system:
      enabled:
        - greetd.service
        - tailscaled.service

  - type: systemd
    user:
      enabled:
        - dms.service
    
