[preferred]
# Use the Hyprland portal for screen sharing and window capturing
default = hyprland;gtk

# Force all sandboxed apps to use the GTK file picker for saving/uploading
org.freedesktop.impl.portal.FileChooser = gtk
org.freedesktop.impl.portal.AppChooser = gtk
