name: Check Fedora 45 COPR Readiness
on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 PM UTC
  workflow_dispatch: # Allows you to run it manually via the website

permissions:
  issues: write

jobs:
  check-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Ping COPRs
        id: check
        run: |
          # Use an if-statement so the script exits successfully even if a 404 is hit
          if curl -sf -o /dev/null "https://copr.fedorainfracloud.org/coprs/avengemedia/danklinux/repo/fedora-45/avengemedia-danklinux-fedora-45.repo" && \
             curl -sf -o /dev/null "https://copr.fedorainfracloud.org/coprs/avengemedia/dms/repo/fedora-45/avengemedia-dms-fedora-45.repo" && \
             curl -sf -o /dev/null "https://copr.fedorainfracloud.org/coprs/nett00n/hyprland/repo/fedora-45/nett00n-hyprland-fedora-45.repo" && \ 
             curl -sf -o /dev/null "https://copr.fedorainfracloud.org/coprs/ferdiu/libfprint-tod/repo/fedora-45/ferdiu-libfprint-tod-fedora-45.repo"; then
            echo "ready=true" >> "$GITHUB_OUTPUT"
          else
            echo "ready=false" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Alert when Ready
        if: steps.check.outputs.ready == 'true' # Only runs if the above script output true
        uses: actions/github-script@v9
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "🚀 All COPRs are Ready for Fedora 45!",
              body: "Update your recipe.yml to image-version: 45. Every single maintainer has successfully built their packages."
            })
