animations {
  enabled = yes

  # The bezier curves
  bezier = overshot, 0.175, 0.885, 0.32, 1.275
  bezier = smoothOut, 0.36, 0, 0.66, -0.56

  # Applying the curves
  animation = windows, 1, 6, overshot, popin 70%
  animation = windowsOut, 1, 4, smoothOut, popin 70%
  animation = windowsMove, 1, 6, overshot
  animation = workspaces, 1, 6, overshot, slide

  # Forces the special workspace to slide down from the top edge
  animation = specialWorkspace, 1, 6, default, slidevert
}
