# Force global dark mode for all GTK4, Libadwaita, and Flatpak applications
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Automatically generate the Downloads, Documents, Pictures, etc. folders and config files
exec-once = xdg-user-dirs-update

exec-once = dms run
exec-once = lxqt-policykit-agent
exec-once = gnome-keyring-daemon --start --components=secrets
#exec-once = quickshell
# Push the Flatpak paths into systemd
exec-once = systemctl --user import-environment XDG_DATA_DIRS

# Restart DMS so it launches with the new paths
exec-once = systemctl --user restart dms.service

