# Force global dark mode for all GTK4, Libadwaita, and Flatpak applications
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = dms run
exec-once = lxqt-policykit-agent
exec-once = gnome-keyring-daemon --start --components=secrets

