exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dms run
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = lxqt-policykit-agent
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle

