# --- Fallback Colors ---
# This file will be automatically overwritten by DankMaterialShell/Matugen 
# the moment you change your wallpaper on the live system.

$primary = rgba(33ccffee)
$surfaceVariant = rgba(222222aa)
$primaryContainer = rgba(1188aaff)
