# --- DMS Master Config ---

# Source Modular Files
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/laptop.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf

# Startup Services
exec-once = dms run
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/libexec/lxqt-policykit-agent


# Core UI Rules
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee)
}

decoration {
    rounding = 10
    blur {
        enabled = true
    }
}
