# --- DMS Master Config (Fully Provisioned) ---

# 1. Source Modular Files
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/ENVariables.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/SystemSettings.conf
source = ~/.config/hypr/laptop.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/Decorations.conf

