$mainMod = SUPER

bind = $mainMod, Enter, exec, kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, C, exit, 
bind = $mainMod, F, exec, nemo
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, dsearch
