# Verified F43 / 0.54+ Syntax

# Force GNOME apps to tile instead of floating
windowrule = match:class ^(org\.gnome\..*)$, tile 1

# NEW IN 0.54: Assign distinct layouts to specific workspaces natively
#workspace = 1, layout:master
#workspace = 2, layout:dwindle
#workspace = 9, layout:scrolling

# Force imv to float and center like a traditional photo viewer
windowrule = match:class ^(imv)$, float 1
windowrule = match:class ^(imv)$, center 1

windowrule = match:class ^(com\.moonlight_stream\.Moonlight)$, workspace 2
